### ISSUE TITLE
Empty result set for the UKMovies pattern

### ISSUE THREAD

**Issue by thSoft** [FTSRG/incqueryd#86]
The UKMovies pattern's result set is empty but it should not be. The Rete network inspector would be very useful to debug this.

**Comment by thSoft** [comment]
A suspicious log entry from the stderr of the Wikidata stream processor Spark executor:
```
15/11/05 16:36:55 ERROR executor.Executor: Exception in task 0.1 in stage 3.0 (TID 72)
java.util.concurrent.TimeoutException: Futures timed out after [30 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:190)
	at hu.bme.mit.incqueryd.spark.workers.InputStreamWorker$$anonfun$process$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$3.apply(InputStreamWorker.scala:52)
	at hu.bme.mit.incqueryd.spark.workers.InputStreamWorker$$anonfun$process$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$3.apply(InputStreamWorker.scala:49)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:79)
	at hu.bme.mit.incqueryd.spark.workers.InputStreamWorker$$anonfun$process$1$$anonfun$apply$1$$anonfun$apply$2.apply(InputStreamWorker.scala:49)
	at hu.bme.mit.incqueryd.spark.workers.InputStreamWorker$$anonfun$process$1$$anonfun$apply$1$$anonfun$apply$2.apply(InputStreamWorker.scala:43)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at hu.bme.mit.incqueryd.spark.workers.InputStreamWorker$$anonfun$process$1$$anonfun$apply$1.apply(InputStreamWorker.scala:43)
	at hu.bme.mit.incqueryd.spark.workers.InputStreamWorker$$anonfun$process$1$$anonfun$apply$1.apply(InputStreamWorker.scala:41)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at org.apache.spark.util.NextIterator.foreach(NextIterator.scala:21)
	at org.apache.spark.rdd.RDD$$anonfun$foreach$1$$anonfun$apply$28.apply(RDD.scala:890)
	at org.apache.spark.rdd.RDD$$anonfun$foreach$1$$anonfun$apply$28.apply(RDD.scala:890)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1839)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1839)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by thSoft** [comment]
Seems like the termination protocol doesn't terminate for this pattern.
